#ifndef _CENTERSERVER_SEND_OP_H
#define _CENTERSERVER_SEND_OP_H

enum CENTER_SERVER_SEND_OP
{
    CENTERSERVER_SEND_OP_RPC,
    CENTERSERVER_SEND_OP_PONG,
    CENTERSERVER_SEND_OP_LOGICSERVER_SELFID,
    CENTERSERVER_SEND_OP_PACKET2CLIENTMIRROR,             /*  中心服务器请求转发数据给玩家  */
    
    CENTERSERVER_SEND_OP_USER,
};

#endif