// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerConfig.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ServerConfig.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ServerConfig {
class CenterServerConfigDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CenterServerConfig> {
} _CenterServerConfig_default_instance_;
class EtcdAddrDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<EtcdAddr> {
} _EtcdAddr_default_instance_;
class ConnectionServerConfigDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ConnectionServerConfig> {
} _ConnectionServerConfig_default_instance_;
class LogicServerConfigDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<LogicServerConfig> {
} _LogicServerConfig_default_instance_;

namespace protobuf_ServerConfig_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[4];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterServerConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterServerConfig, enableipv6_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterServerConfig, bindip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterServerConfig, listenport_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CenterServerConfig, logicserverloginpassword_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EtcdAddr, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EtcdAddr, ip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EtcdAddr, port_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionServerConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionServerConfig, enableipv6_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionServerConfig, bindip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionServerConfig, portforclient_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionServerConfig, portforlogicserver_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionServerConfig, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionServerConfig, etcdservers_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConnectionServerConfig, logicserverloginpassword_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LogicServerConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LogicServerConfig, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LogicServerConfig, isprimary_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LogicServerConfig, etcdservers_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(CenterServerConfig)},
  { 8, -1, sizeof(EtcdAddr)},
  { 14, -1, sizeof(ConnectionServerConfig)},
  { 25, -1, sizeof(LogicServerConfig)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_CenterServerConfig_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_EtcdAddr_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_ConnectionServerConfig_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_LogicServerConfig_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "ServerConfig.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

}  // namespace

void TableStruct::Shutdown() {
  _CenterServerConfig_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _EtcdAddr_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _ConnectionServerConfig_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _LogicServerConfig_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _CenterServerConfig_default_instance_.DefaultConstruct();
  _EtcdAddr_default_instance_.DefaultConstruct();
  _ConnectionServerConfig_default_instance_.DefaultConstruct();
  _LogicServerConfig_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\022ServerConfig.proto\022\014ServerConfig\"n\n\022Ce"
      "nterServerConfig\022\022\n\nenableIPV6\030\001 \001(\010\022\016\n\006"
      "bindIP\030\002 \001(\t\022\022\n\nlistenPort\030\003 \001(\005\022 \n\030logi"
      "cServerLoginPassword\030\004 \001(\t\"$\n\010EtcdAddr\022\n"
      "\n\002ip\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\"\312\001\n\026ConnectionS"
      "erverConfig\022\022\n\nenableIPV6\030\001 \001(\010\022\016\n\006bindI"
      "P\030\002 \001(\t\022\025\n\rportForClient\030\003 \001(\005\022\032\n\022portFo"
      "rLogicServer\030\004 \001(\005\022\n\n\002id\030\005 \001(\005\022+\n\013etcdse"
      "rvers\030\006 \003(\0132\026.ServerConfig.EtcdAddr\022 \n\030l"
      "ogicServerLoginPassword\030\007 \001(\t\"_\n\021LogicSe"
      "rverConfig\022\n\n\002id\030\001 \001(\005\022\021\n\tisPrimary\030\002 \001("
      "\010\022+\n\013etcdservers\030\003 \003(\0132\026.ServerConfig.Et"
      "cdAddrb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 494);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ServerConfig.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_ServerConfig_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CenterServerConfig::kEnableIPV6FieldNumber;
const int CenterServerConfig::kBindIPFieldNumber;
const int CenterServerConfig::kListenPortFieldNumber;
const int CenterServerConfig::kLogicServerLoginPasswordFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CenterServerConfig::CenterServerConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_ServerConfig_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ServerConfig.CenterServerConfig)
}
CenterServerConfig::CenterServerConfig(const CenterServerConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  bindip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.bindip().size() > 0) {
    bindip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bindip_);
  }
  logicserverloginpassword_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.logicserverloginpassword().size() > 0) {
    logicserverloginpassword_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.logicserverloginpassword_);
  }
  ::memcpy(&enableipv6_, &from.enableipv6_,
    reinterpret_cast<char*>(&listenport_) -
    reinterpret_cast<char*>(&enableipv6_) + sizeof(listenport_));
  // @@protoc_insertion_point(copy_constructor:ServerConfig.CenterServerConfig)
}

void CenterServerConfig::SharedCtor() {
  bindip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  logicserverloginpassword_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&enableipv6_, 0, reinterpret_cast<char*>(&listenport_) -
    reinterpret_cast<char*>(&enableipv6_) + sizeof(listenport_));
  _cached_size_ = 0;
}

CenterServerConfig::~CenterServerConfig() {
  // @@protoc_insertion_point(destructor:ServerConfig.CenterServerConfig)
  SharedDtor();
}

void CenterServerConfig::SharedDtor() {
  bindip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  logicserverloginpassword_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CenterServerConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CenterServerConfig::descriptor() {
  protobuf_ServerConfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_ServerConfig_2eproto::file_level_metadata[0].descriptor;
}

const CenterServerConfig& CenterServerConfig::default_instance() {
  protobuf_ServerConfig_2eproto::InitDefaults();
  return *internal_default_instance();
}

CenterServerConfig* CenterServerConfig::New(::google::protobuf::Arena* arena) const {
  CenterServerConfig* n = new CenterServerConfig;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CenterServerConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:ServerConfig.CenterServerConfig)
  bindip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  logicserverloginpassword_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&enableipv6_, 0, reinterpret_cast<char*>(&listenport_) -
    reinterpret_cast<char*>(&enableipv6_) + sizeof(listenport_));
}

bool CenterServerConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ServerConfig.CenterServerConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool enableIPV6 = 1;
      case 1: {
        if (tag == 8u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &enableipv6_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string bindIP = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_bindip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->bindip().data(), this->bindip().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ServerConfig.CenterServerConfig.bindIP"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 listenPort = 3;
      case 3: {
        if (tag == 24u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &listenport_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string logicServerLoginPassword = 4;
      case 4: {
        if (tag == 34u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_logicserverloginpassword()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->logicserverloginpassword().data(), this->logicserverloginpassword().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ServerConfig.CenterServerConfig.logicServerLoginPassword"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ServerConfig.CenterServerConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ServerConfig.CenterServerConfig)
  return false;
#undef DO_
}

void CenterServerConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ServerConfig.CenterServerConfig)
  // bool enableIPV6 = 1;
  if (this->enableipv6() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->enableipv6(), output);
  }

  // string bindIP = 2;
  if (this->bindip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->bindip().data(), this->bindip().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ServerConfig.CenterServerConfig.bindIP");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->bindip(), output);
  }

  // int32 listenPort = 3;
  if (this->listenport() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->listenport(), output);
  }

  // string logicServerLoginPassword = 4;
  if (this->logicserverloginpassword().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->logicserverloginpassword().data(), this->logicserverloginpassword().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ServerConfig.CenterServerConfig.logicServerLoginPassword");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->logicserverloginpassword(), output);
  }

  // @@protoc_insertion_point(serialize_end:ServerConfig.CenterServerConfig)
}

::google::protobuf::uint8* CenterServerConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ServerConfig.CenterServerConfig)
  // bool enableIPV6 = 1;
  if (this->enableipv6() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->enableipv6(), target);
  }

  // string bindIP = 2;
  if (this->bindip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->bindip().data(), this->bindip().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ServerConfig.CenterServerConfig.bindIP");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->bindip(), target);
  }

  // int32 listenPort = 3;
  if (this->listenport() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->listenport(), target);
  }

  // string logicServerLoginPassword = 4;
  if (this->logicserverloginpassword().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->logicserverloginpassword().data(), this->logicserverloginpassword().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ServerConfig.CenterServerConfig.logicServerLoginPassword");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->logicserverloginpassword(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:ServerConfig.CenterServerConfig)
  return target;
}

size_t CenterServerConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ServerConfig.CenterServerConfig)
  size_t total_size = 0;

  // string bindIP = 2;
  if (this->bindip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->bindip());
  }

  // string logicServerLoginPassword = 4;
  if (this->logicserverloginpassword().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->logicserverloginpassword());
  }

  // bool enableIPV6 = 1;
  if (this->enableipv6() != 0) {
    total_size += 1 + 1;
  }

  // int32 listenPort = 3;
  if (this->listenport() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->listenport());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CenterServerConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ServerConfig.CenterServerConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const CenterServerConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CenterServerConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ServerConfig.CenterServerConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ServerConfig.CenterServerConfig)
    MergeFrom(*source);
  }
}

void CenterServerConfig::MergeFrom(const CenterServerConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ServerConfig.CenterServerConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.bindip().size() > 0) {

    bindip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bindip_);
  }
  if (from.logicserverloginpassword().size() > 0) {

    logicserverloginpassword_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.logicserverloginpassword_);
  }
  if (from.enableipv6() != 0) {
    set_enableipv6(from.enableipv6());
  }
  if (from.listenport() != 0) {
    set_listenport(from.listenport());
  }
}

void CenterServerConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ServerConfig.CenterServerConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CenterServerConfig::CopyFrom(const CenterServerConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ServerConfig.CenterServerConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CenterServerConfig::IsInitialized() const {
  return true;
}

void CenterServerConfig::Swap(CenterServerConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CenterServerConfig::InternalSwap(CenterServerConfig* other) {
  bindip_.Swap(&other->bindip_);
  logicserverloginpassword_.Swap(&other->logicserverloginpassword_);
  std::swap(enableipv6_, other->enableipv6_);
  std::swap(listenport_, other->listenport_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CenterServerConfig::GetMetadata() const {
  protobuf_ServerConfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_ServerConfig_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CenterServerConfig

// bool enableIPV6 = 1;
void CenterServerConfig::clear_enableipv6() {
  enableipv6_ = false;
}
bool CenterServerConfig::enableipv6() const {
  // @@protoc_insertion_point(field_get:ServerConfig.CenterServerConfig.enableIPV6)
  return enableipv6_;
}
void CenterServerConfig::set_enableipv6(bool value) {
  
  enableipv6_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.CenterServerConfig.enableIPV6)
}

// string bindIP = 2;
void CenterServerConfig::clear_bindip() {
  bindip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CenterServerConfig::bindip() const {
  // @@protoc_insertion_point(field_get:ServerConfig.CenterServerConfig.bindIP)
  return bindip_.GetNoArena();
}
void CenterServerConfig::set_bindip(const ::std::string& value) {
  
  bindip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ServerConfig.CenterServerConfig.bindIP)
}
#if LANG_CXX11
void CenterServerConfig::set_bindip(::std::string&& value) {
  
  bindip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ServerConfig.CenterServerConfig.bindIP)
}
#endif
void CenterServerConfig::set_bindip(const char* value) {
  
  bindip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ServerConfig.CenterServerConfig.bindIP)
}
void CenterServerConfig::set_bindip(const char* value, size_t size) {
  
  bindip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ServerConfig.CenterServerConfig.bindIP)
}
::std::string* CenterServerConfig::mutable_bindip() {
  
  // @@protoc_insertion_point(field_mutable:ServerConfig.CenterServerConfig.bindIP)
  return bindip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CenterServerConfig::release_bindip() {
  // @@protoc_insertion_point(field_release:ServerConfig.CenterServerConfig.bindIP)
  
  return bindip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CenterServerConfig::set_allocated_bindip(::std::string* bindip) {
  if (bindip != NULL) {
    
  } else {
    
  }
  bindip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bindip);
  // @@protoc_insertion_point(field_set_allocated:ServerConfig.CenterServerConfig.bindIP)
}

// int32 listenPort = 3;
void CenterServerConfig::clear_listenport() {
  listenport_ = 0;
}
::google::protobuf::int32 CenterServerConfig::listenport() const {
  // @@protoc_insertion_point(field_get:ServerConfig.CenterServerConfig.listenPort)
  return listenport_;
}
void CenterServerConfig::set_listenport(::google::protobuf::int32 value) {
  
  listenport_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.CenterServerConfig.listenPort)
}

// string logicServerLoginPassword = 4;
void CenterServerConfig::clear_logicserverloginpassword() {
  logicserverloginpassword_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CenterServerConfig::logicserverloginpassword() const {
  // @@protoc_insertion_point(field_get:ServerConfig.CenterServerConfig.logicServerLoginPassword)
  return logicserverloginpassword_.GetNoArena();
}
void CenterServerConfig::set_logicserverloginpassword(const ::std::string& value) {
  
  logicserverloginpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ServerConfig.CenterServerConfig.logicServerLoginPassword)
}
#if LANG_CXX11
void CenterServerConfig::set_logicserverloginpassword(::std::string&& value) {
  
  logicserverloginpassword_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ServerConfig.CenterServerConfig.logicServerLoginPassword)
}
#endif
void CenterServerConfig::set_logicserverloginpassword(const char* value) {
  
  logicserverloginpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ServerConfig.CenterServerConfig.logicServerLoginPassword)
}
void CenterServerConfig::set_logicserverloginpassword(const char* value, size_t size) {
  
  logicserverloginpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ServerConfig.CenterServerConfig.logicServerLoginPassword)
}
::std::string* CenterServerConfig::mutable_logicserverloginpassword() {
  
  // @@protoc_insertion_point(field_mutable:ServerConfig.CenterServerConfig.logicServerLoginPassword)
  return logicserverloginpassword_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CenterServerConfig::release_logicserverloginpassword() {
  // @@protoc_insertion_point(field_release:ServerConfig.CenterServerConfig.logicServerLoginPassword)
  
  return logicserverloginpassword_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CenterServerConfig::set_allocated_logicserverloginpassword(::std::string* logicserverloginpassword) {
  if (logicserverloginpassword != NULL) {
    
  } else {
    
  }
  logicserverloginpassword_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), logicserverloginpassword);
  // @@protoc_insertion_point(field_set_allocated:ServerConfig.CenterServerConfig.logicServerLoginPassword)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EtcdAddr::kIpFieldNumber;
const int EtcdAddr::kPortFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EtcdAddr::EtcdAddr()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_ServerConfig_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ServerConfig.EtcdAddr)
}
EtcdAddr::EtcdAddr(const EtcdAddr& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ip().size() > 0) {
    ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ip_);
  }
  port_ = from.port_;
  // @@protoc_insertion_point(copy_constructor:ServerConfig.EtcdAddr)
}

void EtcdAddr::SharedCtor() {
  ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  port_ = 0;
  _cached_size_ = 0;
}

EtcdAddr::~EtcdAddr() {
  // @@protoc_insertion_point(destructor:ServerConfig.EtcdAddr)
  SharedDtor();
}

void EtcdAddr::SharedDtor() {
  ip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void EtcdAddr::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* EtcdAddr::descriptor() {
  protobuf_ServerConfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_ServerConfig_2eproto::file_level_metadata[1].descriptor;
}

const EtcdAddr& EtcdAddr::default_instance() {
  protobuf_ServerConfig_2eproto::InitDefaults();
  return *internal_default_instance();
}

EtcdAddr* EtcdAddr::New(::google::protobuf::Arena* arena) const {
  EtcdAddr* n = new EtcdAddr;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void EtcdAddr::Clear() {
// @@protoc_insertion_point(message_clear_start:ServerConfig.EtcdAddr)
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  port_ = 0;
}

bool EtcdAddr::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ServerConfig.EtcdAddr)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string ip = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ip().data(), this->ip().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ServerConfig.EtcdAddr.ip"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 port = 2;
      case 2: {
        if (tag == 16u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &port_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ServerConfig.EtcdAddr)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ServerConfig.EtcdAddr)
  return false;
#undef DO_
}

void EtcdAddr::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ServerConfig.EtcdAddr)
  // string ip = 1;
  if (this->ip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ip().data(), this->ip().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ServerConfig.EtcdAddr.ip");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->ip(), output);
  }

  // int32 port = 2;
  if (this->port() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->port(), output);
  }

  // @@protoc_insertion_point(serialize_end:ServerConfig.EtcdAddr)
}

::google::protobuf::uint8* EtcdAddr::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ServerConfig.EtcdAddr)
  // string ip = 1;
  if (this->ip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ip().data(), this->ip().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ServerConfig.EtcdAddr.ip");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->ip(), target);
  }

  // int32 port = 2;
  if (this->port() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->port(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:ServerConfig.EtcdAddr)
  return target;
}

size_t EtcdAddr::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ServerConfig.EtcdAddr)
  size_t total_size = 0;

  // string ip = 1;
  if (this->ip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ip());
  }

  // int32 port = 2;
  if (this->port() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->port());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void EtcdAddr::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ServerConfig.EtcdAddr)
  GOOGLE_DCHECK_NE(&from, this);
  const EtcdAddr* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const EtcdAddr>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ServerConfig.EtcdAddr)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ServerConfig.EtcdAddr)
    MergeFrom(*source);
  }
}

void EtcdAddr::MergeFrom(const EtcdAddr& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ServerConfig.EtcdAddr)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.ip().size() > 0) {

    ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ip_);
  }
  if (from.port() != 0) {
    set_port(from.port());
  }
}

void EtcdAddr::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ServerConfig.EtcdAddr)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EtcdAddr::CopyFrom(const EtcdAddr& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ServerConfig.EtcdAddr)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EtcdAddr::IsInitialized() const {
  return true;
}

void EtcdAddr::Swap(EtcdAddr* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EtcdAddr::InternalSwap(EtcdAddr* other) {
  ip_.Swap(&other->ip_);
  std::swap(port_, other->port_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata EtcdAddr::GetMetadata() const {
  protobuf_ServerConfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_ServerConfig_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// EtcdAddr

// string ip = 1;
void EtcdAddr::clear_ip() {
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& EtcdAddr::ip() const {
  // @@protoc_insertion_point(field_get:ServerConfig.EtcdAddr.ip)
  return ip_.GetNoArena();
}
void EtcdAddr::set_ip(const ::std::string& value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ServerConfig.EtcdAddr.ip)
}
#if LANG_CXX11
void EtcdAddr::set_ip(::std::string&& value) {
  
  ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ServerConfig.EtcdAddr.ip)
}
#endif
void EtcdAddr::set_ip(const char* value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ServerConfig.EtcdAddr.ip)
}
void EtcdAddr::set_ip(const char* value, size_t size) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ServerConfig.EtcdAddr.ip)
}
::std::string* EtcdAddr::mutable_ip() {
  
  // @@protoc_insertion_point(field_mutable:ServerConfig.EtcdAddr.ip)
  return ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* EtcdAddr::release_ip() {
  // @@protoc_insertion_point(field_release:ServerConfig.EtcdAddr.ip)
  
  return ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void EtcdAddr::set_allocated_ip(::std::string* ip) {
  if (ip != NULL) {
    
  } else {
    
  }
  ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:ServerConfig.EtcdAddr.ip)
}

// int32 port = 2;
void EtcdAddr::clear_port() {
  port_ = 0;
}
::google::protobuf::int32 EtcdAddr::port() const {
  // @@protoc_insertion_point(field_get:ServerConfig.EtcdAddr.port)
  return port_;
}
void EtcdAddr::set_port(::google::protobuf::int32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.EtcdAddr.port)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ConnectionServerConfig::kEnableIPV6FieldNumber;
const int ConnectionServerConfig::kBindIPFieldNumber;
const int ConnectionServerConfig::kPortForClientFieldNumber;
const int ConnectionServerConfig::kPortForLogicServerFieldNumber;
const int ConnectionServerConfig::kIdFieldNumber;
const int ConnectionServerConfig::kEtcdserversFieldNumber;
const int ConnectionServerConfig::kLogicServerLoginPasswordFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConnectionServerConfig::ConnectionServerConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_ServerConfig_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ServerConfig.ConnectionServerConfig)
}
ConnectionServerConfig::ConnectionServerConfig(const ConnectionServerConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      etcdservers_(from.etcdservers_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  bindip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.bindip().size() > 0) {
    bindip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bindip_);
  }
  logicserverloginpassword_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.logicserverloginpassword().size() > 0) {
    logicserverloginpassword_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.logicserverloginpassword_);
  }
  ::memcpy(&enableipv6_, &from.enableipv6_,
    reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&enableipv6_) + sizeof(id_));
  // @@protoc_insertion_point(copy_constructor:ServerConfig.ConnectionServerConfig)
}

void ConnectionServerConfig::SharedCtor() {
  bindip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  logicserverloginpassword_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&enableipv6_, 0, reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&enableipv6_) + sizeof(id_));
  _cached_size_ = 0;
}

ConnectionServerConfig::~ConnectionServerConfig() {
  // @@protoc_insertion_point(destructor:ServerConfig.ConnectionServerConfig)
  SharedDtor();
}

void ConnectionServerConfig::SharedDtor() {
  bindip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  logicserverloginpassword_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ConnectionServerConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ConnectionServerConfig::descriptor() {
  protobuf_ServerConfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_ServerConfig_2eproto::file_level_metadata[2].descriptor;
}

const ConnectionServerConfig& ConnectionServerConfig::default_instance() {
  protobuf_ServerConfig_2eproto::InitDefaults();
  return *internal_default_instance();
}

ConnectionServerConfig* ConnectionServerConfig::New(::google::protobuf::Arena* arena) const {
  ConnectionServerConfig* n = new ConnectionServerConfig;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ConnectionServerConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:ServerConfig.ConnectionServerConfig)
  etcdservers_.Clear();
  bindip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  logicserverloginpassword_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&enableipv6_, 0, reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&enableipv6_) + sizeof(id_));
}

bool ConnectionServerConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ServerConfig.ConnectionServerConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool enableIPV6 = 1;
      case 1: {
        if (tag == 8u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &enableipv6_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string bindIP = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_bindip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->bindip().data(), this->bindip().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ServerConfig.ConnectionServerConfig.bindIP"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 portForClient = 3;
      case 3: {
        if (tag == 24u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &portforclient_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 portForLogicServer = 4;
      case 4: {
        if (tag == 32u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &portforlogicserver_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 id = 5;
      case 5: {
        if (tag == 40u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .ServerConfig.EtcdAddr etcdservers = 6;
      case 6: {
        if (tag == 50u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_etcdservers()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // string logicServerLoginPassword = 7;
      case 7: {
        if (tag == 58u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_logicserverloginpassword()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->logicserverloginpassword().data(), this->logicserverloginpassword().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ServerConfig.ConnectionServerConfig.logicServerLoginPassword"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ServerConfig.ConnectionServerConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ServerConfig.ConnectionServerConfig)
  return false;
#undef DO_
}

void ConnectionServerConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ServerConfig.ConnectionServerConfig)
  // bool enableIPV6 = 1;
  if (this->enableipv6() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->enableipv6(), output);
  }

  // string bindIP = 2;
  if (this->bindip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->bindip().data(), this->bindip().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ServerConfig.ConnectionServerConfig.bindIP");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->bindip(), output);
  }

  // int32 portForClient = 3;
  if (this->portforclient() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->portforclient(), output);
  }

  // int32 portForLogicServer = 4;
  if (this->portforlogicserver() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->portforlogicserver(), output);
  }

  // int32 id = 5;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->id(), output);
  }

  // repeated .ServerConfig.EtcdAddr etcdservers = 6;
  for (unsigned int i = 0, n = this->etcdservers_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->etcdservers(i), output);
  }

  // string logicServerLoginPassword = 7;
  if (this->logicserverloginpassword().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->logicserverloginpassword().data(), this->logicserverloginpassword().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ServerConfig.ConnectionServerConfig.logicServerLoginPassword");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->logicserverloginpassword(), output);
  }

  // @@protoc_insertion_point(serialize_end:ServerConfig.ConnectionServerConfig)
}

::google::protobuf::uint8* ConnectionServerConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ServerConfig.ConnectionServerConfig)
  // bool enableIPV6 = 1;
  if (this->enableipv6() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->enableipv6(), target);
  }

  // string bindIP = 2;
  if (this->bindip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->bindip().data(), this->bindip().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ServerConfig.ConnectionServerConfig.bindIP");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->bindip(), target);
  }

  // int32 portForClient = 3;
  if (this->portforclient() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->portforclient(), target);
  }

  // int32 portForLogicServer = 4;
  if (this->portforlogicserver() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->portforlogicserver(), target);
  }

  // int32 id = 5;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->id(), target);
  }

  // repeated .ServerConfig.EtcdAddr etcdservers = 6;
  for (unsigned int i = 0, n = this->etcdservers_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        6, this->etcdservers(i), false, target);
  }

  // string logicServerLoginPassword = 7;
  if (this->logicserverloginpassword().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->logicserverloginpassword().data(), this->logicserverloginpassword().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ServerConfig.ConnectionServerConfig.logicServerLoginPassword");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->logicserverloginpassword(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:ServerConfig.ConnectionServerConfig)
  return target;
}

size_t ConnectionServerConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ServerConfig.ConnectionServerConfig)
  size_t total_size = 0;

  // repeated .ServerConfig.EtcdAddr etcdservers = 6;
  {
    unsigned int count = this->etcdservers_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->etcdservers(i));
    }
  }

  // string bindIP = 2;
  if (this->bindip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->bindip());
  }

  // string logicServerLoginPassword = 7;
  if (this->logicserverloginpassword().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->logicserverloginpassword());
  }

  // bool enableIPV6 = 1;
  if (this->enableipv6() != 0) {
    total_size += 1 + 1;
  }

  // int32 portForClient = 3;
  if (this->portforclient() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->portforclient());
  }

  // int32 portForLogicServer = 4;
  if (this->portforlogicserver() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->portforlogicserver());
  }

  // int32 id = 5;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ConnectionServerConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ServerConfig.ConnectionServerConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const ConnectionServerConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ConnectionServerConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ServerConfig.ConnectionServerConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ServerConfig.ConnectionServerConfig)
    MergeFrom(*source);
  }
}

void ConnectionServerConfig::MergeFrom(const ConnectionServerConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ServerConfig.ConnectionServerConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  etcdservers_.MergeFrom(from.etcdservers_);
  if (from.bindip().size() > 0) {

    bindip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bindip_);
  }
  if (from.logicserverloginpassword().size() > 0) {

    logicserverloginpassword_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.logicserverloginpassword_);
  }
  if (from.enableipv6() != 0) {
    set_enableipv6(from.enableipv6());
  }
  if (from.portforclient() != 0) {
    set_portforclient(from.portforclient());
  }
  if (from.portforlogicserver() != 0) {
    set_portforlogicserver(from.portforlogicserver());
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
}

void ConnectionServerConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ServerConfig.ConnectionServerConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConnectionServerConfig::CopyFrom(const ConnectionServerConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ServerConfig.ConnectionServerConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConnectionServerConfig::IsInitialized() const {
  return true;
}

void ConnectionServerConfig::Swap(ConnectionServerConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConnectionServerConfig::InternalSwap(ConnectionServerConfig* other) {
  etcdservers_.UnsafeArenaSwap(&other->etcdservers_);
  bindip_.Swap(&other->bindip_);
  logicserverloginpassword_.Swap(&other->logicserverloginpassword_);
  std::swap(enableipv6_, other->enableipv6_);
  std::swap(portforclient_, other->portforclient_);
  std::swap(portforlogicserver_, other->portforlogicserver_);
  std::swap(id_, other->id_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ConnectionServerConfig::GetMetadata() const {
  protobuf_ServerConfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_ServerConfig_2eproto::file_level_metadata[2];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ConnectionServerConfig

// bool enableIPV6 = 1;
void ConnectionServerConfig::clear_enableipv6() {
  enableipv6_ = false;
}
bool ConnectionServerConfig::enableipv6() const {
  // @@protoc_insertion_point(field_get:ServerConfig.ConnectionServerConfig.enableIPV6)
  return enableipv6_;
}
void ConnectionServerConfig::set_enableipv6(bool value) {
  
  enableipv6_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.ConnectionServerConfig.enableIPV6)
}

// string bindIP = 2;
void ConnectionServerConfig::clear_bindip() {
  bindip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& ConnectionServerConfig::bindip() const {
  // @@protoc_insertion_point(field_get:ServerConfig.ConnectionServerConfig.bindIP)
  return bindip_.GetNoArena();
}
void ConnectionServerConfig::set_bindip(const ::std::string& value) {
  
  bindip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ServerConfig.ConnectionServerConfig.bindIP)
}
#if LANG_CXX11
void ConnectionServerConfig::set_bindip(::std::string&& value) {
  
  bindip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ServerConfig.ConnectionServerConfig.bindIP)
}
#endif
void ConnectionServerConfig::set_bindip(const char* value) {
  
  bindip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ServerConfig.ConnectionServerConfig.bindIP)
}
void ConnectionServerConfig::set_bindip(const char* value, size_t size) {
  
  bindip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ServerConfig.ConnectionServerConfig.bindIP)
}
::std::string* ConnectionServerConfig::mutable_bindip() {
  
  // @@protoc_insertion_point(field_mutable:ServerConfig.ConnectionServerConfig.bindIP)
  return bindip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ConnectionServerConfig::release_bindip() {
  // @@protoc_insertion_point(field_release:ServerConfig.ConnectionServerConfig.bindIP)
  
  return bindip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ConnectionServerConfig::set_allocated_bindip(::std::string* bindip) {
  if (bindip != NULL) {
    
  } else {
    
  }
  bindip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bindip);
  // @@protoc_insertion_point(field_set_allocated:ServerConfig.ConnectionServerConfig.bindIP)
}

// int32 portForClient = 3;
void ConnectionServerConfig::clear_portforclient() {
  portforclient_ = 0;
}
::google::protobuf::int32 ConnectionServerConfig::portforclient() const {
  // @@protoc_insertion_point(field_get:ServerConfig.ConnectionServerConfig.portForClient)
  return portforclient_;
}
void ConnectionServerConfig::set_portforclient(::google::protobuf::int32 value) {
  
  portforclient_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.ConnectionServerConfig.portForClient)
}

// int32 portForLogicServer = 4;
void ConnectionServerConfig::clear_portforlogicserver() {
  portforlogicserver_ = 0;
}
::google::protobuf::int32 ConnectionServerConfig::portforlogicserver() const {
  // @@protoc_insertion_point(field_get:ServerConfig.ConnectionServerConfig.portForLogicServer)
  return portforlogicserver_;
}
void ConnectionServerConfig::set_portforlogicserver(::google::protobuf::int32 value) {
  
  portforlogicserver_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.ConnectionServerConfig.portForLogicServer)
}

// int32 id = 5;
void ConnectionServerConfig::clear_id() {
  id_ = 0;
}
::google::protobuf::int32 ConnectionServerConfig::id() const {
  // @@protoc_insertion_point(field_get:ServerConfig.ConnectionServerConfig.id)
  return id_;
}
void ConnectionServerConfig::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.ConnectionServerConfig.id)
}

// repeated .ServerConfig.EtcdAddr etcdservers = 6;
int ConnectionServerConfig::etcdservers_size() const {
  return etcdservers_.size();
}
void ConnectionServerConfig::clear_etcdservers() {
  etcdservers_.Clear();
}
const ::ServerConfig::EtcdAddr& ConnectionServerConfig::etcdservers(int index) const {
  // @@protoc_insertion_point(field_get:ServerConfig.ConnectionServerConfig.etcdservers)
  return etcdservers_.Get(index);
}
::ServerConfig::EtcdAddr* ConnectionServerConfig::mutable_etcdservers(int index) {
  // @@protoc_insertion_point(field_mutable:ServerConfig.ConnectionServerConfig.etcdservers)
  return etcdservers_.Mutable(index);
}
::ServerConfig::EtcdAddr* ConnectionServerConfig::add_etcdservers() {
  // @@protoc_insertion_point(field_add:ServerConfig.ConnectionServerConfig.etcdservers)
  return etcdservers_.Add();
}
::google::protobuf::RepeatedPtrField< ::ServerConfig::EtcdAddr >*
ConnectionServerConfig::mutable_etcdservers() {
  // @@protoc_insertion_point(field_mutable_list:ServerConfig.ConnectionServerConfig.etcdservers)
  return &etcdservers_;
}
const ::google::protobuf::RepeatedPtrField< ::ServerConfig::EtcdAddr >&
ConnectionServerConfig::etcdservers() const {
  // @@protoc_insertion_point(field_list:ServerConfig.ConnectionServerConfig.etcdservers)
  return etcdservers_;
}

// string logicServerLoginPassword = 7;
void ConnectionServerConfig::clear_logicserverloginpassword() {
  logicserverloginpassword_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& ConnectionServerConfig::logicserverloginpassword() const {
  // @@protoc_insertion_point(field_get:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
  return logicserverloginpassword_.GetNoArena();
}
void ConnectionServerConfig::set_logicserverloginpassword(const ::std::string& value) {
  
  logicserverloginpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
}
#if LANG_CXX11
void ConnectionServerConfig::set_logicserverloginpassword(::std::string&& value) {
  
  logicserverloginpassword_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
}
#endif
void ConnectionServerConfig::set_logicserverloginpassword(const char* value) {
  
  logicserverloginpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
}
void ConnectionServerConfig::set_logicserverloginpassword(const char* value, size_t size) {
  
  logicserverloginpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
}
::std::string* ConnectionServerConfig::mutable_logicserverloginpassword() {
  
  // @@protoc_insertion_point(field_mutable:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
  return logicserverloginpassword_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ConnectionServerConfig::release_logicserverloginpassword() {
  // @@protoc_insertion_point(field_release:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
  
  return logicserverloginpassword_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ConnectionServerConfig::set_allocated_logicserverloginpassword(::std::string* logicserverloginpassword) {
  if (logicserverloginpassword != NULL) {
    
  } else {
    
  }
  logicserverloginpassword_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), logicserverloginpassword);
  // @@protoc_insertion_point(field_set_allocated:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LogicServerConfig::kIdFieldNumber;
const int LogicServerConfig::kIsPrimaryFieldNumber;
const int LogicServerConfig::kEtcdserversFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LogicServerConfig::LogicServerConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_ServerConfig_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ServerConfig.LogicServerConfig)
}
LogicServerConfig::LogicServerConfig(const LogicServerConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      etcdservers_(from.etcdservers_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    reinterpret_cast<char*>(&isprimary_) -
    reinterpret_cast<char*>(&id_) + sizeof(isprimary_));
  // @@protoc_insertion_point(copy_constructor:ServerConfig.LogicServerConfig)
}

void LogicServerConfig::SharedCtor() {
  ::memset(&id_, 0, reinterpret_cast<char*>(&isprimary_) -
    reinterpret_cast<char*>(&id_) + sizeof(isprimary_));
  _cached_size_ = 0;
}

LogicServerConfig::~LogicServerConfig() {
  // @@protoc_insertion_point(destructor:ServerConfig.LogicServerConfig)
  SharedDtor();
}

void LogicServerConfig::SharedDtor() {
}

void LogicServerConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LogicServerConfig::descriptor() {
  protobuf_ServerConfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_ServerConfig_2eproto::file_level_metadata[3].descriptor;
}

const LogicServerConfig& LogicServerConfig::default_instance() {
  protobuf_ServerConfig_2eproto::InitDefaults();
  return *internal_default_instance();
}

LogicServerConfig* LogicServerConfig::New(::google::protobuf::Arena* arena) const {
  LogicServerConfig* n = new LogicServerConfig;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LogicServerConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:ServerConfig.LogicServerConfig)
  etcdservers_.Clear();
  ::memset(&id_, 0, reinterpret_cast<char*>(&isprimary_) -
    reinterpret_cast<char*>(&id_) + sizeof(isprimary_));
}

bool LogicServerConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ServerConfig.LogicServerConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 id = 1;
      case 1: {
        if (tag == 8u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool isPrimary = 2;
      case 2: {
        if (tag == 16u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isprimary_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .ServerConfig.EtcdAddr etcdservers = 3;
      case 3: {
        if (tag == 26u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_etcdservers()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ServerConfig.LogicServerConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ServerConfig.LogicServerConfig)
  return false;
#undef DO_
}

void LogicServerConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ServerConfig.LogicServerConfig)
  // int32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // bool isPrimary = 2;
  if (this->isprimary() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->isprimary(), output);
  }

  // repeated .ServerConfig.EtcdAddr etcdservers = 3;
  for (unsigned int i = 0, n = this->etcdservers_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->etcdservers(i), output);
  }

  // @@protoc_insertion_point(serialize_end:ServerConfig.LogicServerConfig)
}

::google::protobuf::uint8* LogicServerConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ServerConfig.LogicServerConfig)
  // int32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // bool isPrimary = 2;
  if (this->isprimary() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->isprimary(), target);
  }

  // repeated .ServerConfig.EtcdAddr etcdservers = 3;
  for (unsigned int i = 0, n = this->etcdservers_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->etcdservers(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:ServerConfig.LogicServerConfig)
  return target;
}

size_t LogicServerConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ServerConfig.LogicServerConfig)
  size_t total_size = 0;

  // repeated .ServerConfig.EtcdAddr etcdservers = 3;
  {
    unsigned int count = this->etcdservers_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->etcdservers(i));
    }
  }

  // int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  // bool isPrimary = 2;
  if (this->isprimary() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LogicServerConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ServerConfig.LogicServerConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const LogicServerConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LogicServerConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ServerConfig.LogicServerConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ServerConfig.LogicServerConfig)
    MergeFrom(*source);
  }
}

void LogicServerConfig::MergeFrom(const LogicServerConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ServerConfig.LogicServerConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  etcdservers_.MergeFrom(from.etcdservers_);
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.isprimary() != 0) {
    set_isprimary(from.isprimary());
  }
}

void LogicServerConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ServerConfig.LogicServerConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LogicServerConfig::CopyFrom(const LogicServerConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ServerConfig.LogicServerConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogicServerConfig::IsInitialized() const {
  return true;
}

void LogicServerConfig::Swap(LogicServerConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LogicServerConfig::InternalSwap(LogicServerConfig* other) {
  etcdservers_.UnsafeArenaSwap(&other->etcdservers_);
  std::swap(id_, other->id_);
  std::swap(isprimary_, other->isprimary_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LogicServerConfig::GetMetadata() const {
  protobuf_ServerConfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_ServerConfig_2eproto::file_level_metadata[3];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LogicServerConfig

// int32 id = 1;
void LogicServerConfig::clear_id() {
  id_ = 0;
}
::google::protobuf::int32 LogicServerConfig::id() const {
  // @@protoc_insertion_point(field_get:ServerConfig.LogicServerConfig.id)
  return id_;
}
void LogicServerConfig::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.LogicServerConfig.id)
}

// bool isPrimary = 2;
void LogicServerConfig::clear_isprimary() {
  isprimary_ = false;
}
bool LogicServerConfig::isprimary() const {
  // @@protoc_insertion_point(field_get:ServerConfig.LogicServerConfig.isPrimary)
  return isprimary_;
}
void LogicServerConfig::set_isprimary(bool value) {
  
  isprimary_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.LogicServerConfig.isPrimary)
}

// repeated .ServerConfig.EtcdAddr etcdservers = 3;
int LogicServerConfig::etcdservers_size() const {
  return etcdservers_.size();
}
void LogicServerConfig::clear_etcdservers() {
  etcdservers_.Clear();
}
const ::ServerConfig::EtcdAddr& LogicServerConfig::etcdservers(int index) const {
  // @@protoc_insertion_point(field_get:ServerConfig.LogicServerConfig.etcdservers)
  return etcdservers_.Get(index);
}
::ServerConfig::EtcdAddr* LogicServerConfig::mutable_etcdservers(int index) {
  // @@protoc_insertion_point(field_mutable:ServerConfig.LogicServerConfig.etcdservers)
  return etcdservers_.Mutable(index);
}
::ServerConfig::EtcdAddr* LogicServerConfig::add_etcdservers() {
  // @@protoc_insertion_point(field_add:ServerConfig.LogicServerConfig.etcdservers)
  return etcdservers_.Add();
}
::google::protobuf::RepeatedPtrField< ::ServerConfig::EtcdAddr >*
LogicServerConfig::mutable_etcdservers() {
  // @@protoc_insertion_point(field_mutable_list:ServerConfig.LogicServerConfig.etcdservers)
  return &etcdservers_;
}
const ::google::protobuf::RepeatedPtrField< ::ServerConfig::EtcdAddr >&
LogicServerConfig::etcdservers() const {
  // @@protoc_insertion_point(field_list:ServerConfig.LogicServerConfig.etcdservers)
  return etcdservers_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ServerConfig

// @@protoc_insertion_point(global_scope)
