// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerConfig.proto

#ifndef PROTOBUF_ServerConfig_2eproto__INCLUDED
#define PROTOBUF_ServerConfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace ServerConfig {
class CenterServerConfig;
class CenterServerConfigDefaultTypeInternal;
extern CenterServerConfigDefaultTypeInternal _CenterServerConfig_default_instance_;
class ConnectionServerConfig;
class ConnectionServerConfigDefaultTypeInternal;
extern ConnectionServerConfigDefaultTypeInternal _ConnectionServerConfig_default_instance_;
class EtcdAddr;
class EtcdAddrDefaultTypeInternal;
extern EtcdAddrDefaultTypeInternal _EtcdAddr_default_instance_;
class LogicServerConfig;
class LogicServerConfigDefaultTypeInternal;
extern LogicServerConfigDefaultTypeInternal _LogicServerConfig_default_instance_;
}  // namespace ServerConfig

namespace ServerConfig {

namespace protobuf_ServerConfig_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_ServerConfig_2eproto

// ===================================================================

class CenterServerConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ServerConfig.CenterServerConfig) */ {
 public:
  CenterServerConfig();
  virtual ~CenterServerConfig();

  CenterServerConfig(const CenterServerConfig& from);

  inline CenterServerConfig& operator=(const CenterServerConfig& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CenterServerConfig& default_instance();

  static inline const CenterServerConfig* internal_default_instance() {
    return reinterpret_cast<const CenterServerConfig*>(
               &_CenterServerConfig_default_instance_);
  }

  void Swap(CenterServerConfig* other);

  // implements Message ----------------------------------------------

  inline CenterServerConfig* New() const PROTOBUF_FINAL { return New(NULL); }

  CenterServerConfig* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CenterServerConfig& from);
  void MergeFrom(const CenterServerConfig& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CenterServerConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string bindIP = 2;
  void clear_bindip();
  static const int kBindIPFieldNumber = 2;
  const ::std::string& bindip() const;
  void set_bindip(const ::std::string& value);
  #if LANG_CXX11
  void set_bindip(::std::string&& value);
  #endif
  void set_bindip(const char* value);
  void set_bindip(const char* value, size_t size);
  ::std::string* mutable_bindip();
  ::std::string* release_bindip();
  void set_allocated_bindip(::std::string* bindip);

  // string logicServerLoginPassword = 4;
  void clear_logicserverloginpassword();
  static const int kLogicServerLoginPasswordFieldNumber = 4;
  const ::std::string& logicserverloginpassword() const;
  void set_logicserverloginpassword(const ::std::string& value);
  #if LANG_CXX11
  void set_logicserverloginpassword(::std::string&& value);
  #endif
  void set_logicserverloginpassword(const char* value);
  void set_logicserverloginpassword(const char* value, size_t size);
  ::std::string* mutable_logicserverloginpassword();
  ::std::string* release_logicserverloginpassword();
  void set_allocated_logicserverloginpassword(::std::string* logicserverloginpassword);

  // bool enableIPV6 = 1;
  void clear_enableipv6();
  static const int kEnableIPV6FieldNumber = 1;
  bool enableipv6() const;
  void set_enableipv6(bool value);

  // int32 listenPort = 3;
  void clear_listenport();
  static const int kListenPortFieldNumber = 3;
  ::google::protobuf::int32 listenport() const;
  void set_listenport(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ServerConfig.CenterServerConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr bindip_;
  ::google::protobuf::internal::ArenaStringPtr logicserverloginpassword_;
  bool enableipv6_;
  ::google::protobuf::int32 listenport_;
  mutable int _cached_size_;
  friend struct  protobuf_ServerConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class EtcdAddr : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ServerConfig.EtcdAddr) */ {
 public:
  EtcdAddr();
  virtual ~EtcdAddr();

  EtcdAddr(const EtcdAddr& from);

  inline EtcdAddr& operator=(const EtcdAddr& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EtcdAddr& default_instance();

  static inline const EtcdAddr* internal_default_instance() {
    return reinterpret_cast<const EtcdAddr*>(
               &_EtcdAddr_default_instance_);
  }

  void Swap(EtcdAddr* other);

  // implements Message ----------------------------------------------

  inline EtcdAddr* New() const PROTOBUF_FINAL { return New(NULL); }

  EtcdAddr* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const EtcdAddr& from);
  void MergeFrom(const EtcdAddr& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(EtcdAddr* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string ip = 1;
  void clear_ip();
  static const int kIpFieldNumber = 1;
  const ::std::string& ip() const;
  void set_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_ip(::std::string&& value);
  #endif
  void set_ip(const char* value);
  void set_ip(const char* value, size_t size);
  ::std::string* mutable_ip();
  ::std::string* release_ip();
  void set_allocated_ip(::std::string* ip);

  // int32 port = 2;
  void clear_port();
  static const int kPortFieldNumber = 2;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ServerConfig.EtcdAddr)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr ip_;
  ::google::protobuf::int32 port_;
  mutable int _cached_size_;
  friend struct  protobuf_ServerConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ConnectionServerConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ServerConfig.ConnectionServerConfig) */ {
 public:
  ConnectionServerConfig();
  virtual ~ConnectionServerConfig();

  ConnectionServerConfig(const ConnectionServerConfig& from);

  inline ConnectionServerConfig& operator=(const ConnectionServerConfig& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConnectionServerConfig& default_instance();

  static inline const ConnectionServerConfig* internal_default_instance() {
    return reinterpret_cast<const ConnectionServerConfig*>(
               &_ConnectionServerConfig_default_instance_);
  }

  void Swap(ConnectionServerConfig* other);

  // implements Message ----------------------------------------------

  inline ConnectionServerConfig* New() const PROTOBUF_FINAL { return New(NULL); }

  ConnectionServerConfig* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ConnectionServerConfig& from);
  void MergeFrom(const ConnectionServerConfig& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ConnectionServerConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ServerConfig.EtcdAddr etcdservers = 6;
  int etcdservers_size() const;
  void clear_etcdservers();
  static const int kEtcdserversFieldNumber = 6;
  const ::ServerConfig::EtcdAddr& etcdservers(int index) const;
  ::ServerConfig::EtcdAddr* mutable_etcdservers(int index);
  ::ServerConfig::EtcdAddr* add_etcdservers();
  ::google::protobuf::RepeatedPtrField< ::ServerConfig::EtcdAddr >*
      mutable_etcdservers();
  const ::google::protobuf::RepeatedPtrField< ::ServerConfig::EtcdAddr >&
      etcdservers() const;

  // string bindIP = 2;
  void clear_bindip();
  static const int kBindIPFieldNumber = 2;
  const ::std::string& bindip() const;
  void set_bindip(const ::std::string& value);
  #if LANG_CXX11
  void set_bindip(::std::string&& value);
  #endif
  void set_bindip(const char* value);
  void set_bindip(const char* value, size_t size);
  ::std::string* mutable_bindip();
  ::std::string* release_bindip();
  void set_allocated_bindip(::std::string* bindip);

  // string logicServerLoginPassword = 7;
  void clear_logicserverloginpassword();
  static const int kLogicServerLoginPasswordFieldNumber = 7;
  const ::std::string& logicserverloginpassword() const;
  void set_logicserverloginpassword(const ::std::string& value);
  #if LANG_CXX11
  void set_logicserverloginpassword(::std::string&& value);
  #endif
  void set_logicserverloginpassword(const char* value);
  void set_logicserverloginpassword(const char* value, size_t size);
  ::std::string* mutable_logicserverloginpassword();
  ::std::string* release_logicserverloginpassword();
  void set_allocated_logicserverloginpassword(::std::string* logicserverloginpassword);

  // bool enableIPV6 = 1;
  void clear_enableipv6();
  static const int kEnableIPV6FieldNumber = 1;
  bool enableipv6() const;
  void set_enableipv6(bool value);

  // int32 portForClient = 3;
  void clear_portforclient();
  static const int kPortForClientFieldNumber = 3;
  ::google::protobuf::int32 portforclient() const;
  void set_portforclient(::google::protobuf::int32 value);

  // int32 portForLogicServer = 4;
  void clear_portforlogicserver();
  static const int kPortForLogicServerFieldNumber = 4;
  ::google::protobuf::int32 portforlogicserver() const;
  void set_portforlogicserver(::google::protobuf::int32 value);

  // int32 id = 5;
  void clear_id();
  static const int kIdFieldNumber = 5;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ServerConfig.ConnectionServerConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ServerConfig::EtcdAddr > etcdservers_;
  ::google::protobuf::internal::ArenaStringPtr bindip_;
  ::google::protobuf::internal::ArenaStringPtr logicserverloginpassword_;
  bool enableipv6_;
  ::google::protobuf::int32 portforclient_;
  ::google::protobuf::int32 portforlogicserver_;
  ::google::protobuf::int32 id_;
  mutable int _cached_size_;
  friend struct  protobuf_ServerConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LogicServerConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ServerConfig.LogicServerConfig) */ {
 public:
  LogicServerConfig();
  virtual ~LogicServerConfig();

  LogicServerConfig(const LogicServerConfig& from);

  inline LogicServerConfig& operator=(const LogicServerConfig& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogicServerConfig& default_instance();

  static inline const LogicServerConfig* internal_default_instance() {
    return reinterpret_cast<const LogicServerConfig*>(
               &_LogicServerConfig_default_instance_);
  }

  void Swap(LogicServerConfig* other);

  // implements Message ----------------------------------------------

  inline LogicServerConfig* New() const PROTOBUF_FINAL { return New(NULL); }

  LogicServerConfig* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LogicServerConfig& from);
  void MergeFrom(const LogicServerConfig& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LogicServerConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ServerConfig.EtcdAddr etcdservers = 3;
  int etcdservers_size() const;
  void clear_etcdservers();
  static const int kEtcdserversFieldNumber = 3;
  const ::ServerConfig::EtcdAddr& etcdservers(int index) const;
  ::ServerConfig::EtcdAddr* mutable_etcdservers(int index);
  ::ServerConfig::EtcdAddr* add_etcdservers();
  ::google::protobuf::RepeatedPtrField< ::ServerConfig::EtcdAddr >*
      mutable_etcdservers();
  const ::google::protobuf::RepeatedPtrField< ::ServerConfig::EtcdAddr >&
      etcdservers() const;

  // int32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // bool isPrimary = 2;
  void clear_isprimary();
  static const int kIsPrimaryFieldNumber = 2;
  bool isprimary() const;
  void set_isprimary(bool value);

  // @@protoc_insertion_point(class_scope:ServerConfig.LogicServerConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ServerConfig::EtcdAddr > etcdservers_;
  ::google::protobuf::int32 id_;
  bool isprimary_;
  mutable int _cached_size_;
  friend struct  protobuf_ServerConfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CenterServerConfig

// bool enableIPV6 = 1;
inline void CenterServerConfig::clear_enableipv6() {
  enableipv6_ = false;
}
inline bool CenterServerConfig::enableipv6() const {
  // @@protoc_insertion_point(field_get:ServerConfig.CenterServerConfig.enableIPV6)
  return enableipv6_;
}
inline void CenterServerConfig::set_enableipv6(bool value) {
  
  enableipv6_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.CenterServerConfig.enableIPV6)
}

// string bindIP = 2;
inline void CenterServerConfig::clear_bindip() {
  bindip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CenterServerConfig::bindip() const {
  // @@protoc_insertion_point(field_get:ServerConfig.CenterServerConfig.bindIP)
  return bindip_.GetNoArena();
}
inline void CenterServerConfig::set_bindip(const ::std::string& value) {
  
  bindip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ServerConfig.CenterServerConfig.bindIP)
}
#if LANG_CXX11
inline void CenterServerConfig::set_bindip(::std::string&& value) {
  
  bindip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ServerConfig.CenterServerConfig.bindIP)
}
#endif
inline void CenterServerConfig::set_bindip(const char* value) {
  
  bindip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ServerConfig.CenterServerConfig.bindIP)
}
inline void CenterServerConfig::set_bindip(const char* value, size_t size) {
  
  bindip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ServerConfig.CenterServerConfig.bindIP)
}
inline ::std::string* CenterServerConfig::mutable_bindip() {
  
  // @@protoc_insertion_point(field_mutable:ServerConfig.CenterServerConfig.bindIP)
  return bindip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CenterServerConfig::release_bindip() {
  // @@protoc_insertion_point(field_release:ServerConfig.CenterServerConfig.bindIP)
  
  return bindip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CenterServerConfig::set_allocated_bindip(::std::string* bindip) {
  if (bindip != NULL) {
    
  } else {
    
  }
  bindip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bindip);
  // @@protoc_insertion_point(field_set_allocated:ServerConfig.CenterServerConfig.bindIP)
}

// int32 listenPort = 3;
inline void CenterServerConfig::clear_listenport() {
  listenport_ = 0;
}
inline ::google::protobuf::int32 CenterServerConfig::listenport() const {
  // @@protoc_insertion_point(field_get:ServerConfig.CenterServerConfig.listenPort)
  return listenport_;
}
inline void CenterServerConfig::set_listenport(::google::protobuf::int32 value) {
  
  listenport_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.CenterServerConfig.listenPort)
}

// string logicServerLoginPassword = 4;
inline void CenterServerConfig::clear_logicserverloginpassword() {
  logicserverloginpassword_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CenterServerConfig::logicserverloginpassword() const {
  // @@protoc_insertion_point(field_get:ServerConfig.CenterServerConfig.logicServerLoginPassword)
  return logicserverloginpassword_.GetNoArena();
}
inline void CenterServerConfig::set_logicserverloginpassword(const ::std::string& value) {
  
  logicserverloginpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ServerConfig.CenterServerConfig.logicServerLoginPassword)
}
#if LANG_CXX11
inline void CenterServerConfig::set_logicserverloginpassword(::std::string&& value) {
  
  logicserverloginpassword_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ServerConfig.CenterServerConfig.logicServerLoginPassword)
}
#endif
inline void CenterServerConfig::set_logicserverloginpassword(const char* value) {
  
  logicserverloginpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ServerConfig.CenterServerConfig.logicServerLoginPassword)
}
inline void CenterServerConfig::set_logicserverloginpassword(const char* value, size_t size) {
  
  logicserverloginpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ServerConfig.CenterServerConfig.logicServerLoginPassword)
}
inline ::std::string* CenterServerConfig::mutable_logicserverloginpassword() {
  
  // @@protoc_insertion_point(field_mutable:ServerConfig.CenterServerConfig.logicServerLoginPassword)
  return logicserverloginpassword_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CenterServerConfig::release_logicserverloginpassword() {
  // @@protoc_insertion_point(field_release:ServerConfig.CenterServerConfig.logicServerLoginPassword)
  
  return logicserverloginpassword_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CenterServerConfig::set_allocated_logicserverloginpassword(::std::string* logicserverloginpassword) {
  if (logicserverloginpassword != NULL) {
    
  } else {
    
  }
  logicserverloginpassword_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), logicserverloginpassword);
  // @@protoc_insertion_point(field_set_allocated:ServerConfig.CenterServerConfig.logicServerLoginPassword)
}

// -------------------------------------------------------------------

// EtcdAddr

// string ip = 1;
inline void EtcdAddr::clear_ip() {
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& EtcdAddr::ip() const {
  // @@protoc_insertion_point(field_get:ServerConfig.EtcdAddr.ip)
  return ip_.GetNoArena();
}
inline void EtcdAddr::set_ip(const ::std::string& value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ServerConfig.EtcdAddr.ip)
}
#if LANG_CXX11
inline void EtcdAddr::set_ip(::std::string&& value) {
  
  ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ServerConfig.EtcdAddr.ip)
}
#endif
inline void EtcdAddr::set_ip(const char* value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ServerConfig.EtcdAddr.ip)
}
inline void EtcdAddr::set_ip(const char* value, size_t size) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ServerConfig.EtcdAddr.ip)
}
inline ::std::string* EtcdAddr::mutable_ip() {
  
  // @@protoc_insertion_point(field_mutable:ServerConfig.EtcdAddr.ip)
  return ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* EtcdAddr::release_ip() {
  // @@protoc_insertion_point(field_release:ServerConfig.EtcdAddr.ip)
  
  return ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void EtcdAddr::set_allocated_ip(::std::string* ip) {
  if (ip != NULL) {
    
  } else {
    
  }
  ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:ServerConfig.EtcdAddr.ip)
}

// int32 port = 2;
inline void EtcdAddr::clear_port() {
  port_ = 0;
}
inline ::google::protobuf::int32 EtcdAddr::port() const {
  // @@protoc_insertion_point(field_get:ServerConfig.EtcdAddr.port)
  return port_;
}
inline void EtcdAddr::set_port(::google::protobuf::int32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.EtcdAddr.port)
}

// -------------------------------------------------------------------

// ConnectionServerConfig

// bool enableIPV6 = 1;
inline void ConnectionServerConfig::clear_enableipv6() {
  enableipv6_ = false;
}
inline bool ConnectionServerConfig::enableipv6() const {
  // @@protoc_insertion_point(field_get:ServerConfig.ConnectionServerConfig.enableIPV6)
  return enableipv6_;
}
inline void ConnectionServerConfig::set_enableipv6(bool value) {
  
  enableipv6_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.ConnectionServerConfig.enableIPV6)
}

// string bindIP = 2;
inline void ConnectionServerConfig::clear_bindip() {
  bindip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConnectionServerConfig::bindip() const {
  // @@protoc_insertion_point(field_get:ServerConfig.ConnectionServerConfig.bindIP)
  return bindip_.GetNoArena();
}
inline void ConnectionServerConfig::set_bindip(const ::std::string& value) {
  
  bindip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ServerConfig.ConnectionServerConfig.bindIP)
}
#if LANG_CXX11
inline void ConnectionServerConfig::set_bindip(::std::string&& value) {
  
  bindip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ServerConfig.ConnectionServerConfig.bindIP)
}
#endif
inline void ConnectionServerConfig::set_bindip(const char* value) {
  
  bindip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ServerConfig.ConnectionServerConfig.bindIP)
}
inline void ConnectionServerConfig::set_bindip(const char* value, size_t size) {
  
  bindip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ServerConfig.ConnectionServerConfig.bindIP)
}
inline ::std::string* ConnectionServerConfig::mutable_bindip() {
  
  // @@protoc_insertion_point(field_mutable:ServerConfig.ConnectionServerConfig.bindIP)
  return bindip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConnectionServerConfig::release_bindip() {
  // @@protoc_insertion_point(field_release:ServerConfig.ConnectionServerConfig.bindIP)
  
  return bindip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConnectionServerConfig::set_allocated_bindip(::std::string* bindip) {
  if (bindip != NULL) {
    
  } else {
    
  }
  bindip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bindip);
  // @@protoc_insertion_point(field_set_allocated:ServerConfig.ConnectionServerConfig.bindIP)
}

// int32 portForClient = 3;
inline void ConnectionServerConfig::clear_portforclient() {
  portforclient_ = 0;
}
inline ::google::protobuf::int32 ConnectionServerConfig::portforclient() const {
  // @@protoc_insertion_point(field_get:ServerConfig.ConnectionServerConfig.portForClient)
  return portforclient_;
}
inline void ConnectionServerConfig::set_portforclient(::google::protobuf::int32 value) {
  
  portforclient_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.ConnectionServerConfig.portForClient)
}

// int32 portForLogicServer = 4;
inline void ConnectionServerConfig::clear_portforlogicserver() {
  portforlogicserver_ = 0;
}
inline ::google::protobuf::int32 ConnectionServerConfig::portforlogicserver() const {
  // @@protoc_insertion_point(field_get:ServerConfig.ConnectionServerConfig.portForLogicServer)
  return portforlogicserver_;
}
inline void ConnectionServerConfig::set_portforlogicserver(::google::protobuf::int32 value) {
  
  portforlogicserver_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.ConnectionServerConfig.portForLogicServer)
}

// int32 id = 5;
inline void ConnectionServerConfig::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 ConnectionServerConfig::id() const {
  // @@protoc_insertion_point(field_get:ServerConfig.ConnectionServerConfig.id)
  return id_;
}
inline void ConnectionServerConfig::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.ConnectionServerConfig.id)
}

// repeated .ServerConfig.EtcdAddr etcdservers = 6;
inline int ConnectionServerConfig::etcdservers_size() const {
  return etcdservers_.size();
}
inline void ConnectionServerConfig::clear_etcdservers() {
  etcdservers_.Clear();
}
inline const ::ServerConfig::EtcdAddr& ConnectionServerConfig::etcdservers(int index) const {
  // @@protoc_insertion_point(field_get:ServerConfig.ConnectionServerConfig.etcdservers)
  return etcdservers_.Get(index);
}
inline ::ServerConfig::EtcdAddr* ConnectionServerConfig::mutable_etcdservers(int index) {
  // @@protoc_insertion_point(field_mutable:ServerConfig.ConnectionServerConfig.etcdservers)
  return etcdservers_.Mutable(index);
}
inline ::ServerConfig::EtcdAddr* ConnectionServerConfig::add_etcdservers() {
  // @@protoc_insertion_point(field_add:ServerConfig.ConnectionServerConfig.etcdservers)
  return etcdservers_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ServerConfig::EtcdAddr >*
ConnectionServerConfig::mutable_etcdservers() {
  // @@protoc_insertion_point(field_mutable_list:ServerConfig.ConnectionServerConfig.etcdservers)
  return &etcdservers_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ServerConfig::EtcdAddr >&
ConnectionServerConfig::etcdservers() const {
  // @@protoc_insertion_point(field_list:ServerConfig.ConnectionServerConfig.etcdservers)
  return etcdservers_;
}

// string logicServerLoginPassword = 7;
inline void ConnectionServerConfig::clear_logicserverloginpassword() {
  logicserverloginpassword_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConnectionServerConfig::logicserverloginpassword() const {
  // @@protoc_insertion_point(field_get:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
  return logicserverloginpassword_.GetNoArena();
}
inline void ConnectionServerConfig::set_logicserverloginpassword(const ::std::string& value) {
  
  logicserverloginpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
}
#if LANG_CXX11
inline void ConnectionServerConfig::set_logicserverloginpassword(::std::string&& value) {
  
  logicserverloginpassword_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
}
#endif
inline void ConnectionServerConfig::set_logicserverloginpassword(const char* value) {
  
  logicserverloginpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
}
inline void ConnectionServerConfig::set_logicserverloginpassword(const char* value, size_t size) {
  
  logicserverloginpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
}
inline ::std::string* ConnectionServerConfig::mutable_logicserverloginpassword() {
  
  // @@protoc_insertion_point(field_mutable:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
  return logicserverloginpassword_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConnectionServerConfig::release_logicserverloginpassword() {
  // @@protoc_insertion_point(field_release:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
  
  return logicserverloginpassword_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConnectionServerConfig::set_allocated_logicserverloginpassword(::std::string* logicserverloginpassword) {
  if (logicserverloginpassword != NULL) {
    
  } else {
    
  }
  logicserverloginpassword_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), logicserverloginpassword);
  // @@protoc_insertion_point(field_set_allocated:ServerConfig.ConnectionServerConfig.logicServerLoginPassword)
}

// -------------------------------------------------------------------

// LogicServerConfig

// int32 id = 1;
inline void LogicServerConfig::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 LogicServerConfig::id() const {
  // @@protoc_insertion_point(field_get:ServerConfig.LogicServerConfig.id)
  return id_;
}
inline void LogicServerConfig::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.LogicServerConfig.id)
}

// bool isPrimary = 2;
inline void LogicServerConfig::clear_isprimary() {
  isprimary_ = false;
}
inline bool LogicServerConfig::isprimary() const {
  // @@protoc_insertion_point(field_get:ServerConfig.LogicServerConfig.isPrimary)
  return isprimary_;
}
inline void LogicServerConfig::set_isprimary(bool value) {
  
  isprimary_ = value;
  // @@protoc_insertion_point(field_set:ServerConfig.LogicServerConfig.isPrimary)
}

// repeated .ServerConfig.EtcdAddr etcdservers = 3;
inline int LogicServerConfig::etcdservers_size() const {
  return etcdservers_.size();
}
inline void LogicServerConfig::clear_etcdservers() {
  etcdservers_.Clear();
}
inline const ::ServerConfig::EtcdAddr& LogicServerConfig::etcdservers(int index) const {
  // @@protoc_insertion_point(field_get:ServerConfig.LogicServerConfig.etcdservers)
  return etcdservers_.Get(index);
}
inline ::ServerConfig::EtcdAddr* LogicServerConfig::mutable_etcdservers(int index) {
  // @@protoc_insertion_point(field_mutable:ServerConfig.LogicServerConfig.etcdservers)
  return etcdservers_.Mutable(index);
}
inline ::ServerConfig::EtcdAddr* LogicServerConfig::add_etcdservers() {
  // @@protoc_insertion_point(field_add:ServerConfig.LogicServerConfig.etcdservers)
  return etcdservers_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ServerConfig::EtcdAddr >*
LogicServerConfig::mutable_etcdservers() {
  // @@protoc_insertion_point(field_mutable_list:ServerConfig.LogicServerConfig.etcdservers)
  return &etcdservers_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ServerConfig::EtcdAddr >&
LogicServerConfig::etcdservers() const {
  // @@protoc_insertion_point(field_list:ServerConfig.LogicServerConfig.etcdservers)
  return etcdservers_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace ServerConfig

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServerConfig_2eproto__INCLUDED
